package ts;

/**
	Tuple type implementation generated by dts2hx
**/
@:forward @:forwardStatics extern abstract Tuple16<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(std.Array<Any>) from std.Array<Any> to std.Array<Any> {
	public inline function new(element0:T0, element1:T1, element2:T2, element3:T3, element4:T4, element5:T5, element6:T6, element7:T7, element8:T8, element9:T9, element10:T10, element11:T11, element12:T12, element13:T13, element14:T14, element15:T15) {
		this = [element0, element1, element2, element3, element4, element5, element6, element7, element8, element9, element10, element11, element12, element13, element14, element15];
	}
	public var element0(get, set) : T0;
	inline function get_element0():T0 return cast this[0];
	inline function set_element0(v:T0):T0 return cast this[0] = cast v;
	public var element1(get, set) : T1;
	inline function get_element1():T1 return cast this[1];
	inline function set_element1(v:T1):T1 return cast this[1] = cast v;
	public var element2(get, set) : T2;
	inline function get_element2():T2 return cast this[2];
	inline function set_element2(v:T2):T2 return cast this[2] = cast v;
	public var element3(get, set) : T3;
	inline function get_element3():T3 return cast this[3];
	inline function set_element3(v:T3):T3 return cast this[3] = cast v;
	public var element4(get, set) : T4;
	inline function get_element4():T4 return cast this[4];
	inline function set_element4(v:T4):T4 return cast this[4] = cast v;
	public var element5(get, set) : T5;
	inline function get_element5():T5 return cast this[5];
	inline function set_element5(v:T5):T5 return cast this[5] = cast v;
	public var element6(get, set) : T6;
	inline function get_element6():T6 return cast this[6];
	inline function set_element6(v:T6):T6 return cast this[6] = cast v;
	public var element7(get, set) : T7;
	inline function get_element7():T7 return cast this[7];
	inline function set_element7(v:T7):T7 return cast this[7] = cast v;
	public var element8(get, set) : T8;
	inline function get_element8():T8 return cast this[8];
	inline function set_element8(v:T8):T8 return cast this[8] = cast v;
	public var element9(get, set) : T9;
	inline function get_element9():T9 return cast this[9];
	inline function set_element9(v:T9):T9 return cast this[9] = cast v;
	public var element10(get, set) : T10;
	inline function get_element10():T10 return cast this[10];
	inline function set_element10(v:T10):T10 return cast this[10] = cast v;
	public var element11(get, set) : T11;
	inline function get_element11():T11 return cast this[11];
	inline function set_element11(v:T11):T11 return cast this[11] = cast v;
	public var element12(get, set) : T12;
	inline function get_element12():T12 return cast this[12];
	inline function set_element12(v:T12):T12 return cast this[12] = cast v;
	public var element13(get, set) : T13;
	inline function get_element13():T13 return cast this[13];
	inline function set_element13(v:T13):T13 return cast this[13] = cast v;
	public var element14(get, set) : T14;
	inline function get_element14():T14 return cast this[14];
	inline function set_element14(v:T14):T14 return cast this[14] = cast v;
	public var element15(get, set) : T15;
	inline function get_element15():T15 return cast this[15];
	inline function set_element15(v:T15):T15 return cast this[15] = cast v;
}